# Doctrine MongoDB ODM configuration
doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: '%env(resolve:MONGODB_URL)%'
            options: {}
    default_database: coffee_machine
    types:
        order_id: AlexPerez\CoffeeMachine\Shared\Infrastructure\Persistence\Doctrine\Types\OrderIdType
        money: AlexPerez\CoffeeMachine\Shared\Infrastructure\Persistence\Doctrine\Types\MoneyType
        order_line_id: AlexPerez\CoffeeMachine\Shared\Infrastructure\Persistence\Doctrine\Types\OrderLineIdType
        positive_integer: AlexPerez\CoffeeMachine\Shared\Infrastructure\Persistence\Doctrine\Types\PositiveIntegerType
        order_line: AlexPerez\CoffeeMachine\Shared\Infrastructure\Persistence\Doctrine\Types\OrderLineType
        order_status: AlexPerez\CoffeeMachine\Shared\Infrastructure\Persistence\Doctrine\Types\OrderStatusType
    document_managers:
        default:
            auto_mapping: true
            mappings:
                Order:
                    is_bundle: false
                    type: xml
                    dir: '%kernel.project_dir%/config/doctrine/order'
                    prefix: 'AlexPerez\CoffeeMachine\Order\Order\Domain'
                Sales:
                    is_bundle: false
                    type: xml
                    dir: '%kernel.project_dir%/config/doctrine/sales'
                    prefix: 'AlexPerez\CoffeeMachine\Sales\Order\Domain'
