# Doctrine MongoDB ODM configuration
doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: 'mongodb://root:coffee_machine@mongodb:27017'
            options: {}
    default_database: coffee_machine
    document_managers:
        default:
            auto_mapping: true
            mappings:
                Order:
                    is_bundle: false
                    type: xml
                    dir: '%kernel.project_dir%/config/doctrine/order'
                    prefix: 'AlexPerez\CoffeeMachine\Order\Order\Domain'