services:
    php:
        build:
            dockerfile: docker/images/php-cli/Dockerfile
        volumes:
            - '.:/var/www/html'
        ports:
            - '8080:8000'

    redis:
        image: redis:latest

    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: coffee_machine
            MONGO_INITDB_DATABASE: coffee_machine
        ports:
            - "27017:27017"

    otel-collector:
        image: otel/opentelemetry-collector-contrib:latest
        volumes:
            - ./config/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
        environment:
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_REGION: ${AWS_REGION}
