services:
    php:
        build:
            dockerfile: docker/images/php-cli/Dockerfile
        volumes:
            - '.:/var/www/html'
        ports:
            - '8080:8000'
            - '8081:8081'

    redis:
        image: redis:latest

    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: coffee_machine
            MONGO_INITDB_DATABASE: coffee_machine
        ports:
            - "27017:27017"
