version: '3'

services:
    php:
        build:
            dockerfile: docker/images/php-cli/Dockerfile
        volumes:
            - '.:/var/www/html'
        ports:
            - '8080:8000'

#    mysql:
#        image: mariadb
#        environment:
#            MYSQL_ROOT_PASSWORD: 'coffee_machine'
#            MYSQL_DATABASE: 'coffee_machine'
#            MYSQL_USER: 'coffee_machine'
#            MYSQL_PASSWORD: 'coffee_machine'
#        ports:
#            - "3305:3306"
    redis:
        image: redis:latest

    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: coffee_machine
            MONGO_INITDB_DATABASE: coffee_machine
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:
