imports:
  - { resource: fixtures/products.yaml }
  - { resource: fixtures/promotions.yaml }
tactician:
  commandbus:
    default:
      middleware:
        - tactician.middleware.locking
        - tactician.middleware.command_handler
    query:
      middleware:
        - tactician.commandbus.query.middleware.command_handler

services:
  _defaults:
    autowire: true

  Deliverea\CoffeeMachine\App\:
    resource: '../../app'

  Symfony\Component\Console\Application:
    public: true

  delivera.order.create_handler:
    class: Deliverea\CoffeeMachine\Order\Application\Command\CreateOrderCommandHandler
    tags:
      - { name: tactician.handler, typehints: true, bus: default }

  delivera.line.create_handler:
    class: Deliverea\CoffeeMachine\Order\Application\Command\CreateOrderLineCommandHandler
    tags:
      - { name: tactician.handler, typehints: true, bus: default }

  delivera.order.pay_handler:
    class: Deliverea\CoffeeMachine\Order\Application\Command\PayOrderCommandHandler
    tags:
      - { name: tactician.handler, typehints: true, bus: default }

  deliverea.order.query_handler:
    class: Deliverea\CoffeeMachine\Order\Application\Query\GetOrderQueryHandler
    tags:
      - { name: tactician.handler, command: Deliverea\CoffeeMachine\Order\Infrastructure\Ui\ConsoleQueryObject, bus: query }

  ###Repositories
  delivera.product.in_memory_repository:
    class: Deliverea\CoffeeMachine\Order\Infrastructure\InMemoryProductRepository
    alias:
    arguments:
      - '%products.map.fixtures%'
  Deliverea\CoffeeMachine\Order\Domain\ProductRepositoryInterface: '@delivera.product.in_memory_repository'
  deliverea.order.repository:
    class: Deliverea\CoffeeMachine\Order\Infrastructure\InMemoryOrderRepository
  Deliverea\CoffeeMachine\Order\Domain\OrderRepositoryInterface: '@deliverea.order.repository'

  delivera.promotion.in_memory_repository:
    class: Deliverea\CoffeeMachine\Order\Infrastructure\InMemoryPromotionRepository
    arguments:
      - '%promotions.map.fixtures%'
  Deliverea\CoffeeMachine\Order\Domain\PromotionRepositoryInterface: '@delivera.promotion.in_memory_repository'