imports:
  - { resource: fixtures/products.yaml }
tactician:
  commandbus:
    command:
      middleware:
        - tactician.middleware.locking
        - tactician.middleware.command_handler
    query:
      middleware:
        - tactician.commandbus.query.middleware.command_handler

services:
  _defaults:
    autowire: true

  Deliverea\CoffeeMachine\App\:
    resource: '../../app'

  Symfony\Component\Console\Application:
    public: true

  delivera.product_by_name.query_handler:
    class: Deliverea\CoffeeMachine\Product\Application\Query\GetProductByNameQueryHandler
    arguments:
      - '@delivera.product.in_memory_repository'
    tags:
      - { name: tactician.handler, typehints: true, bus: query }

###Repositories
  delivera.product.in_memory_repository:
    class: Deliverea\CoffeeMachine\Product\Infrastructure\InMemoryProductRepository
    arguments:
      - '%products.map.fixtures%'