imports:
  - { resource: fixtures/products.yaml }
  - { resource: fixtures/promotions.yaml }
tactician:
  commandbus:
    default:
      middleware:
        - tactician.middleware.locking
        - tactician.middleware.command_handler
    query:
      middleware:
        - tactician.commandbus.query.middleware.command_handler

services:
  _defaults:
    autowire: true

  ### Handlers
  Deliverea\CoffeeMachine\App\:
    resource: '../../app'

  Symfony\Component\Console\Application:
    public: true

  delivera.order.create_handler:
    class: Deliverea\CoffeeMachine\Order\Application\Command\CreateOrderCommandHandler
    tags:
      - { name: tactician.handler, typehints: true, bus: default }

  delivera.line.create_handler:
    class: Deliverea\CoffeeMachine\Order\Application\Command\CreateOrderLineCommandHandler
    tags:
      - { name: tactician.handler, typehints: true, bus: default }

  delivera.order.pay_handler:
    class: Deliverea\CoffeeMachine\Order\Application\Command\PayOrderCommandHandler
    tags:
      - { name: tactician.handler, typehints: true, bus: default }

  deliverea.order.query_handler:
    class: Deliverea\CoffeeMachine\Order\Application\Query\GetOrderQueryHandler
    tags:
      - { name: tactician.handler, command: Deliverea\CoffeeMachine\Order\Infrastructure\Ui\ConsoleQueryObject, bus: query }

  deliverea.sales.order_update_handler:
    class: Deliverea\CoffeeMachine\Sales\Application\Command\UpdateOrderLinesCommandHandler
    tags:
      - { name: tactician.handler, typehints: true, bus: default }

  delivera.sales.product_sales_update_handler:
    class: Deliverea\CoffeeMachine\Sales\Application\Command\UpdateSaleCommandHandler
    tags:
      - { name: tactician.handler, typehints: true, bus: default }

  delivera.sales.product_sales_get_all_handler:
    class: Deliverea\CoffeeMachine\Sales\Application\Query\GetAllProductSalesQueryHandler
    tags:
      - { name: tactician.handler, command: Deliverea\CoffeeMachine\Sales\Infrastructure\Ui\ConsoleGetAllProductSalesObject, bus: query }

  ### Subscribers
  delivera.sales.order.subscriber:
    class: Deliverea\CoffeeMachine\Sales\Infrastructure\OrderEventSubscriber
    tags:
      - { name: domain.event_subscriber }

  ### Repositories
  delivera.product.in_memory_repository:
    class: Deliverea\CoffeeMachine\Order\Infrastructure\InMemoryProductRepository
    alias:
    arguments:
      - '%products.map.fixtures%'
  Deliverea\CoffeeMachine\Order\Domain\ProductRepositoryInterface: '@delivera.product.in_memory_repository'
  deliverea.order.repository:
    class: Deliverea\CoffeeMachine\Order\Infrastructure\InMemoryOrderRepository
  Deliverea\CoffeeMachine\Order\Domain\OrderRepositoryInterface: '@deliverea.order.repository'

  deliverea.promotion.in_memory_repository:
    class: Deliverea\CoffeeMachine\Order\Infrastructure\InMemoryPromotionRepository
    arguments:
      - '%promotions.map.fixtures%'
  Deliverea\CoffeeMachine\Order\Domain\PromotionRepositoryInterface: '@deliverea.promotion.in_memory_repository'

  deliverea.sales.order.repository:
    class: Deliverea\CoffeeMachine\Sales\Infrastructure\InMemoryOrderRepository

  Deliverea\CoffeeMachine\Sales\Domain\OrderRepositoryInterface: '@deliverea.sales.order.repository'

  deliverea.sales.product_sales.repository:
    class: Deliverea\CoffeeMachine\Sales\Infrastructure\InFileProductSaleRepository
    arguments:
      - '%env(resolve:DATA_FILE)%'

  Deliverea\CoffeeMachine\Sales\Domain\ProductSaleRepositoryInterface: '@deliverea.sales.product_sales.repository'

  ### Bus
  deliverea.event_bus:
    class: Deliverea\CoffeeMachine\Shared\Infrastructure\Eventbus\EventBusWrapper
  Deliverea\CoffeeMachine\Shared\Domain\EventBus\EventBusInterface: '@deliverea.event_bus'