imports:
    - { resource: fixtures/products.yaml }
    - { resource: fixtures/promotions.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    ### Commands
    AlexPerez\CoffeeMachine\Shared\Infrastructure\Command\:
        resource: '../src/Shared/Infrastructure/Command'

    alex-perez.order.create_handler:
        class: AlexPerez\CoffeeMachine\Order\Order\Application\Command\CreateOrderCommandHandler
        tags:
            - { name: tactician.handler, typehints: true, bus: default }

    alex-perez.line.create_handler:
        class: AlexPerez\CoffeeMachine\Order\Order\Application\Command\CreateOrderLineCommandHandler
        tags:
            - { name: tactician.handler, typehints: true, bus: default }

    alex-perez.order.pay_handler:
        class: AlexPerez\CoffeeMachine\Order\Order\Application\Command\PayOrderCommandHandler
        tags:
            - { name: tactician.handler, typehints: true, bus: default }

    alex-perez.order.query_handler:
        class: AlexPerez\CoffeeMachine\Order\Order\Application\Query\GetOrderQueryHandler
        tags:
            - { name: tactician.handler, command: AlexPerez\CoffeeMachine\Order\Order\Infrastructure\Ui\ConsoleQueryObject, bus: query }

    AlexPerez\CoffeeMachine\Sales\Order\Application\UpdateOrderLines\UpdateOrderLinesCommandHandler:
        tags:
            - { name: tactician.handler, typehints: true, bus: default }

    AlexPerez\CoffeeMachine\Sales\Order\Application\UpdateOrderStatus\UpdateOrderStatusCommandHandler:
        tags:
            - { name: tactician.handler, typehints: true, bus: default }

    AlexPerez\CoffeeMachine\Sales\ProductSales\Application\Command\AccountProductCommandHandler:
        tags:
            - { name: tactician.handler, typehints: true, bus: default }

    alex-perez.sales.product_sales_get_all_handler:
        class: AlexPerez\CoffeeMachine\Sales\ProductSales\Application\Query\GetAllProductSalesQueryHandler
        tags:
            - { name: tactician.handler, command: AlexPerez\CoffeeMachine\Sales\ProductSales\Infrastructure\Ui\ConsoleGetAllProductSalesObject, bus: query }

    ### Subscribers
    AlexPerez\CoffeeMachine\Sales\Order\Infrastructure\OrderEventSubscriber:
        tags:
            - { name: domain.event_subscriber }

    AlexPerez\CoffeeMachine\Sales\ProductSales\Infrastructure\OrderEventSubscriber:
        tags:
            - { name: domain.event_subscriber }

    ### Repositories
    alex-perez.product.in_memory_repository:
        class: AlexPerez\CoffeeMachine\Order\Order\Infrastructure\InMemoryProductRepository
        alias:
        arguments:
            - '%products.map.fixtures%'
    AlexPerez\CoffeeMachine\Order\Order\Domain\ProductRepositoryInterface: '@alex-perez.product.in_memory_repository'
    alex-perez.order.repository:
        class: AlexPerez\CoffeeMachine\Order\Order\Infrastructure\InMemoryOrderRepository
    AlexPerez\CoffeeMachine\Order\Order\Domain\OrderRepositoryInterface: '@alex-perez.order.repository'

    alex-perez.promotion.in_memory_repository:
        class: AlexPerez\CoffeeMachine\Order\Order\Infrastructure\InMemoryPromotionRepository
        arguments:
            - '%promotions.map.fixtures%'
    AlexPerez\CoffeeMachine\Order\Order\Domain\PromotionRepositoryInterface: '@alex-perez.promotion.in_memory_repository'

    alex-perez.sales.order.repository:
        class: AlexPerez\CoffeeMachine\Sales\Order\Infrastructure\InMemoryOrderRepository

    AlexPerez\CoffeeMachine\Sales\Order\Domain\OrderRepositoryInterface: '@alex-perez.sales.order.repository'

    alex-perez.sales.product_sales.repository:
        class: AlexPerez\CoffeeMachine\Sales\ProductSales\Infrastructure\InFileProductSalesRepository
        arguments:
            - '%env(resolve:DATA_FILE)%'

    AlexPerez\CoffeeMachine\Sales\ProductSales\Domain\ProductSalesRepositoryInterface: '@AlexPerez\CoffeeMachine\Sales\ProductSales\Infrastructure\RedisProductSalesRepository'

    AlexPerez\CoffeeMachine\Shared\Infrastructure\Redis\RedisClientFactory:
        arguments:
            $host: redis
            $port: 6379

    alex-perez.shared.redis_client:
        class: Predis\Client
        factory: ['@AlexPerez\CoffeeMachine\Shared\Infrastructure\Redis\RedisClientFactory', 'create']

    AlexPerez\CoffeeMachine\Sales\ProductSales\Infrastructure\RedisProductSalesRepository:
        public: true
        arguments:
            - '@alex-perez.shared.redis_client'

    ### Bus
    alex-perez.event_bus:
        class: AlexPerez\CoffeeMachine\Shared\Infrastructure\Eventbus\EventBusWrapper
    AlexPerez\CoffeeMachine\Shared\Domain\EventBus\EventBusInterface: '@alex-perez.event_bus'